version: '3.8'

services:
  mongo:
      image: mongo:4.0.8
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: samael
        MONGO_INITDB_ROOT_PASSWORD: mongopassword
      ports:
        - '27017:27017'
      volumes:
        - mongo:/var/lib/mongo
  volumes:
    mongo: ~