version: '3.8'

services:
  app:
    build: 
      context: .
    container_name: app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    networks:
      - nodeNetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo:/var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=samael
      - MONGO_INITDB_ROOT_PASSWORD=samael
    networks:
      - nodeNetwork

volumes:
  mongo: ~

networks:
  nodeNetwork: