version: '3.8'

services:
  app:
    build: 
      context: .
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules

  mongo:
    image: mongo:4.0.8
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo

volumes:
  mongo: ~